# Generated by Django 4.1.4 on 2022-12-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_usuario_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apelido',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_de_nascimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='observacao',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
