# Generated by Django 4.1.4 on 2022-12-19 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_usuario_apelido_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
